name: Build executable for python script

on: [push]

jobs:
  build-exe:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    - name: Python Executable Builder Action
      # You may pin to the exact commit or the version.
      # uses: kentsx/Python2Exe@19c006f72ad75562ab3fea363131a3615e5ff17c
      uses: kentsx/Python2Exe@v1.1.1
      with:
        # the main python file (without .py)
        main: reddit-img-parse
        # the dist path
        #dist: # optional, default is ./dist
        # the version of python
        python_version: 3.10 # optional, default is 3.9
        # the version of pyinstaller
        #pyinstaller_version: # optional, default is 6.7
        # the output exe name
        exe_name: reddit-image-parse # optional, default is main
        # whether to install requirements.txt before build, which is in the root dir
        #use-dependencies: # optional, default is true
        # whether to disappear console terminal
        #no-console: # optional, default is true
        # add the icon mark into your executable, the file path of your ico, e.g. logo.png or logo.ico
        #icon: # optional, default is NONE
        # Whether upload the build executable to artifact
        artifact: true # optional
        # The level of compression for Zlib to be applied to the artifact archive, range from 0(no compression) to 9(max compression)
        #compression_level: # optional, default is 6
        # Whether create a release with the executable
        release: false # optional, default is true
        # The Github token. Make sure you have the permission to create release.
        #token: # optional, default is ${{ github.token }}
        # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
        tag: ${{ steps.date.outputs.date }} # optional, default is ${{ github.ref_name }}-Run#${{ github.run_id }}-Attempt#${{ github.run_attempt }}
        # An optional body file for the release. This should be the path to the file
        #bodyfile: # optional, default is 
        # The path of your version.py file (file name can be different). It must contains a variable "VER"
        # version_file_path: # optional, default is 
              
